# Generated by Django 2.2.1 on 2019-11-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0002_remove_examination_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to='examinations.Examination')),
            ],
        ),
    ]
