// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatientDiagnosis.Examinations.Service.Models;

namespace PatientDiagnosis.Examinations.Service.Migrations
{
    [DbContext(typeof(ExaminationDbContext))]
    [Migration("20201004110616_ObservationsAdded")]
    partial class ObservationsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PatientDiagnosis.Common.Models.Entities.Examination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Aphasia")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AtrialFibrillation")
                        .HasColumnName("atrial_fibrillation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BodyWeakness")
                        .HasColumnName("body_weakness")
                        .HasColumnType("boolean");

                    b.Property<int?>("Ckvalue")
                        .HasColumnType("integer");

                    b.Property<int?>("Creatinevalue")
                        .HasColumnType("integer");

                    b.Property<int?>("Dbp")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Dursymptoms")
                        .HasColumnType("integer");

                    b.Property<int?>("Ecgtype")
                        .HasColumnType("integer");

                    b.Property<float>("FirstClassPrediction")
                        .HasColumnType("real");

                    b.Property<bool?>("FirstTia")
                        .HasColumnName("first_tia")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GaitDisturb")
                        .HasColumnName("gait_disturb")
                        .HasColumnType("boolean");

                    b.Property<float?>("Glucosevalue")
                        .HasColumnType("real");

                    b.Property<int?>("Hgbvalue")
                        .HasColumnType("integer");

                    b.Property<bool?>("HighGlucose")
                        .HasColumnName("high_glucose")
                        .HasColumnType("boolean");

                    b.Property<int?>("HrRate")
                        .HasColumnType("integer");

                    b.Property<bool?>("ImgAbnL")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ImgAbnR")
                        .HasColumnType("boolean");

                    b.Property<int?>("Infraction")
                        .HasColumnName("infraction")
                        .HasColumnType("integer");

                    b.Property<int?>("InitialDbp")
                        .HasColumnName("initial_dbp")
                        .HasColumnType("integer");

                    b.Property<int?>("InittiaNumpast")
                        .HasColumnType("integer");

                    b.Property<int?>("MedAnti")
                        .HasColumnType("integer");

                    b.Property<int?>("MedAsa")
                        .HasColumnType("integer");

                    b.Property<int?>("MedClop")
                        .HasColumnType("integer");

                    b.Property<int?>("MedCoum")
                        .HasColumnType("integer");

                    b.Property<int?>("MedDipy")
                        .HasColumnType("integer");

                    b.Property<bool?>("MedIbupLast7days")
                        .HasColumnType("boolean");

                    b.Property<int?>("MedStat")
                        .HasColumnType("integer");

                    b.Property<bool?>("MyAfib")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MyGait")
                        .HasColumnType("boolean");

                    b.Property<int?>("MyInfarct")
                        .HasColumnType("integer");

                    b.Property<bool?>("MyLang_speech")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MySensation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MyVertigo_syncope")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MyWeakness")
                        .HasColumnType("boolean");

                    b.Property<int?>("PatientId")
                        .HasColumnName("patient_id")
                        .HasColumnType("integer");

                    b.Property<bool?>("PeterFlag")
                        .HasColumnType("boolean");

                    b.Property<int?>("Pltvalue")
                        .HasColumnType("integer");

                    b.Property<bool?>("PmedhisAf")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisCad")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisChf")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisCs")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisDem")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisDiab")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisHchol")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisHyp")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisKps")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisPvd")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisSmoker")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PmedhisVhd")
                        .HasColumnType("boolean");

                    b.Property<int?>("Sa02")
                        .HasColumnType("integer");

                    b.Property<int?>("Sbp")
                        .HasColumnType("integer");

                    b.Property<float>("SecondClassPrediction")
                        .HasColumnType("real");

                    b.Property<bool?>("SpeechDif")
                        .HasColumnName("speech_dif")
                        .HasColumnType("boolean");

                    b.Property<int?>("Temperature")
                        .HasColumnType("integer");

                    b.Property<bool?>("TiaInTwoWeeksOccured")
                        .HasColumnType("boolean");

                    b.Property<float?>("Tntvalue")
                        .HasColumnType("real");

                    b.Property<bool?>("UniWeakness_l")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UniWeakness_r")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Vertigo")
                        .HasColumnName("vertigo")
                        .HasColumnType("boolean");

                    b.Property<float?>("Wbcvalue")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Examinations");
                });
#pragma warning restore 612, 618
        }
    }
}
