# Generated by Django 2.2.1 on 2019-11-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='patient_age',
        ),
    ]
