# Generated by Django 3.0.2 on 2020-01-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_remove_examination_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='atrial_fibrillation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='body_weakness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='first_tia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='gait_disturb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='high_glucose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='infraction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='initial_dbp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examination',
            name='speech_dif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examination',
            name='vertigo',
            field=models.BooleanField(default=False),
        ),
    ]
