# Generated by Django 3.0.2 on 2020-01-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_auto_20200105_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='pulse',
        ),
    ]
